# Generated by Django 5.2.13 on 2026-05-11 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalVenda',
            fields=[
                ('id_canal', models.AutoField(primary_key=True, serialize=False)),
                ('nome_canal', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id_categoria_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
                ('rua', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(default='Fortaleza', max_length=100)),
                ('estado', models.CharField(default='CE', max_length=2)),
                ('saldo_pontos', models.IntegerField(default=0)),
                ('aceite_termos', models.BooleanField(default=False)),
                ('data_aceite_termos', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id_filial', models.AutoField(primary_key=True, serialize=False)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pontos_gerados', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Preparando', 'Preparando'), ('Concluido', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20)),
                ('canal_venda', models.CharField(max_length=50)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_raizesnordeste_ru4674539.cliente')),
                ('id_filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_raizesnordeste_ru4674539.filial')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100)),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validade_produto', models.DateField(blank=True, null=True)),
                ('unidade_medida', models.CharField(max_length=20)),
                ('is_sazonal', models.BooleanField(default=False)),
                ('disponivel', models.BooleanField(default=True)),
                ('filiais', models.ManyToManyField(related_name='produtos', to='app_raizesnordeste_ru4674539.filial')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_raizesnordeste_ru4674539.categoriaproduto')),
            ],
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id_item_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_raizesnordeste_ru4674539.pedido')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_raizesnordeste_ru4674539.produto')),
            ],
        ),
    ]
