# Generated by Django 5.2.13 on 2026-05-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_raizesnordeste_ru4674539', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pontos_gerados',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_pagamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='canal_venda',
            field=models.CharField(max_length=20),
        ),
    ]
